services:
  backup-dev:
    image: nexus.jbrmmg.me.uk:8084/backup-dev:latest
    container_name: backup-dev
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8080
      - DB_DEV_BACKUP_SERVER=${DB_DEV_BACKUP_SERVER}
      - DB_DEV_BACKUP_USER=${DB_DEV_BACKUP_USER}
      - DB_DEV_BACKUP_PASSWORD=${DB_DEV_BACKUP_PASSWORD}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    volumes:
      - backup-dev-logs:/app/logs
      - /home/jason/test-backup/etc:/host/etc:ro
      - /home/jason/test-backup/home:/host/home/jason:ro
      - /home/jason/test-backup/import:/var/import
      - /home/jason/test-backup/media:/media
    networks:
      jbr-network:
        aliases:
          - backup

volumes:
  backup-dev-logs:

networks:
  jbr-network:
    external: true
