logging:
  level:
    ROOT: INFO
    com.jbr.middletier: DEBUG
#    org.hibernate.type.descriptor.sql: TRACE

spring:
  liquibase:
    default-schema:
    change-log: classpath:/db/changelog/h2/db.changelog-master.yaml
    contexts: dbg

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      naming:
        physical-strategy: com.jbr.middletier.backup.util.DebugPhysicalNamingStrategyImpl

backup:
  directory:
    name: /home/jason/Working/BackupDev
    days: 5
    zip: /home/jason/Working/BackupDevZip
  schedule: 0 0/1 * ? * *

  db-url: ${db.dev.backup.server}?autoReconnect=true&useSSL=false
  db-username: ${db.dev.backup.user}
  db-password: ${db.dev.backup.password}

  zip-directory: /home/jason/Working/BackupDevZip

server:
  port: 13013

info:
  app:
    version: Debug
