spring:
  datasource:
    url: ${db.dev.backup.server}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.dev.backup.user}
    password: ${db.dev.backup.password}

  application:
    name: Middle Tier Backup (Development)

  h2:
    console:
      enabled: false

logging.file.name: /var/log/jbr/MiddleTier-Backup-DEV.log
logging:
  file:
    max-history: 3
    max-size: 100MB

server:
  port: 10013

backup:
  gather-schedule: 0 0 0 * * ?
  gather-enabled: false
  service-name: middletier-backup-dev
  directory:
    name: /home/jason/Working/Backup
    days: 10
    zip: /home/jason/Working/BackupDevZip
  schedule: 0 13 0/1 * * ?
  enabled: false

  db-url: ${db.dev.backup.server}?autoReconnect=true&useSSL=false
  db-username: ${db.dev.backup.user}
  db-password: ${db.dev.backup.password}

  zip-directory: /home/jason/Working/BackupDevZip

info:
  app:
    version: Development
