spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS TEST;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

  application:
    name: Middle Tier Backup (Debug)

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  liquibase:
    default-schema:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: default

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

backup:
  db-backup-command: mysqldump -h $$server$$ -u $$user$$ -p$$password$$ $$dbname$$ > $$todaydir$$/$$backupname$$/$$output$$.sql
  db-backup-max-time: 600
  ffmpeg-command: ffmpeg -i %%INPUT%% -movflags use_metadata_tags -qscale 0 %%OUTPUT%%
  gather-schedule: 0 0 0 * * ?
  gather-enabled: false
  schedule: 0 20 0/1 * * ?
  enabled: false
  service-name: middletier-backup-dbg
  web-log-url:
  cache-web-log: false
  directory:
    date-format: yyyy-MM-dd
  review-directory: /home/jason/Working/ImportReview
  email:
    host: smtp.ionos.co.uk
    port: 25
    authenticate: true
    user: backups@jbrmmg.me.uk
    password: ${email.pdn.backup.password}
    from: backups@jbrmmg.me.uk
    to: jason@jbrmmg.me.uk
    enabled: false

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false

info:
  app:
    name: "Backup DB"
    description: "Used for regular backups"

