@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
title Original ERD
skinparam linetype ortho
scale 0.75

entity action_confirm {
   * **id** : int <<generated>> **PK**
   ==
   * action : varchar(20)
   * confirmed : bit(1)
   parameter_required : bit(1)
   parameter : varchar(50)
   file_id : int **FK**
   flags : varchar(10)
}

entity file {
   * **id** : int <<generated>> **PK**
   * **name** : varchar(200) **PK**
   ==
   * directory_id : int fk
   classification_id : int fk
   size : int
   date : datetime
   * removed : bit(1)
   md5 : varchar(32)
   flags : varchar(5)
}

entity directory {
  * *id* : int <<generated>> **PK**
  ==
  * source_id : int **FK**
  * path : varchar(200)
  * removed : bit(1)
}

entity classification {
  * **id** : int <<generated>> **PK**
  ==
  * order int
  regex : varchar(50)
  icon : varchar(60)
  * action : varchar(20)
  * useMD5 : bit(1)
  type : varchar(30)
  is_image : bit(1)
  is_video : bit(1)
}

entity backup {
  * **id** : char(4) **PK**
  ==
  * type : varchar(50)
  * directory : varchar(300)
  * artifact : varchar(100)
  * backupname : varchar(35)
  * filename : varchar(100)
  * time : int
}

entity hardware {
  * **macAddress** : char(17) **PK**
  ==
  * reservedIP : char(1)
  IP : varchar(15)
  * name : varchar(200)
}

entity ignore_file {
  * **id** : int <<generated>> **PK**
  ==
  * name : varchar(100)
  * size : varchar(10)
  * date : datetime
  * md5 : varchar(32)
}

entity import_file {
  * **id** : int <<generated>> **PK**
  ==
  * status : varchar(20)
  file_id : int **FK**
}

entity location {
  * **id** : int **PK**
  ==
  * name : varchar(100)
  * size : varchar(10)
  check_duplicates : bit(1)
}

entity source {
  * **id** : int **PK**
  ==
  * path : varchar(200)
  * location : int **FK**
  status : varchar(15)
  filter : varchar(60)
  destination : int
  source_type : varchar(3)
}

entity synchronize {
 * **id** : int **PK**
 ==
 * source : int **FK**
 * destination : int **FK**
}

action_confirm }o--|| file : fk_action_file
file }|--|| directory : fk_directory_file
file }|--|| classification : fk_classification_file
import_file }|--|| file : fk_import_file
synchronize }|--|| source : fk_destination_synchronize
synchronize }|--|| source : fk_source_synchronize
source |o--o{ location : fk_location_source
directory |o--o{ source : fk_source_directory
@enduml
