@startuml
skinparam entityFontSize 12
skinparam arrowFontSize 9
skinparam linetype ortho
title Refactored ERD
top to bottom direction

entity file_system_object {
  * **id : int <<generated>>**
  ==
  type : char(4)
  name : varchar(200)
  parent : int **//(FK1)//**
  parent_type : char(4)
}

entity file {
   * **id : int //(FK1)//**
   ==
   classification_id : int **//(FK2)//**
   size : int
   date : datetime
   removed : bit(1)
   md5 : varchar(32)
   flags : varchar(5)
   ==
   type = FILE
}

entity image_file {
   * **id : int //(FK1)//**
   ==
   --type indicator--
   //IMGE//
}

entity video_file {
   * **id : int //(PK)(FK1)//**
   ==
   --type indicator--
   //VIDO//
}

entity ignore_file {
  * **id : int //(FK1)//**
  ==
  --type indicator--
  //IGNO//
}

entity import_file {
  * **id : int //(FK1)//**
  ==
  status : varchar(20)
  --type indicator--
  //IMPO//
}

entity directory {
  * **id : int //(FK1)//**
  ==
  removed : bit(1)
  flat : bit(1)
  --type indicator--
  //DIRY//
}

entity source {
  * **id : int //(FK1)//**
  ==
  location : int **//(FK2)//**
  status : varchar(15)
  filter : varchar(60)
  source_type : varchar(3)
  --type indicator--
  //SRCE//
}

entity import_source {
  * **id : int //(FK1)//**
  ==
  destination : int **FK**
  --type indicator--
  //IMPS//
}

entity classification {
  * **id : int <<generated>>**
  ==
  order int
  regex : varchar(50)
  icon : varchar(60)
  action : varchar(20)
  useMD5 : bit(1)
  type : varchar(30)
  is_image : bit(1)
  is_video : bit(1)
}

entity backup {
  * **id : char(4)**
  ==
  type : varchar(50)
  directory : varchar(300)
  artifact : varchar(100)
  backup_name : varchar(35)
  filename : varchar(100)
  time : int
}

entity hardware {
  * **macAddress : char(17)**
  ==
  reservedIP : char(1)
  IP : varchar(15)
  name : varchar(200)
}

entity location {
  * **id : int**
  ==
  name : varchar(100)
  size : varchar(10)
  check_duplicates : bit(1)
}

entity synchronize {
 * **id : int**
 ==
 source : int **//(FK1)//**
 destination : int **//(FK2)//**
}

entity action_confirm {
   * **id : int <<generated>>**
   ==
   action : varchar(20)
   confirmed : bit(1)
   parameter_required : bit(1)
   parameter : varchar(50)
   file_id : int **//(FK1)//**
   flags : varchar(10)
}

file_system_object   |o-d-|| file_system_object : FK1:fk_fso_parent
file                 |o-r-|| file_system_object : FK1:fk_fso_file
directory            |o-r-|| file_system_object : FK1:fk_fso_directory
source               |o-r-|| file_system_object : FK1:fk_fso_source
image_file           |o-r-|| file               : FK1:fk_file_image
video_file           |o-r-|| file               : FK1:fk_file_video
ignore_file          |o-r-|| file               : FK1:fk_file_ignore
import_file          |o-l-|| file               : FK1:fk_file_import
import_source        ||-u-o| source             : FK1:fk_source_import
file                 }|-l-|| classification     : FK2:fk_classification_file
source               }|-d-|| location           : FK2:fk_location_source
synchronize          }|-d-|| source             : FK1:fk_source_sync_src
synchronize          }|-d-|| source             : FK2:fk_source_sync_dst
action_confirm       }o-d-|| file               : FK1:fk_action_file

image_file           ||-[hidden]d-|| video_file
video_file           ||-[hidden]d-|| ignore_file
ignore_file          ||-[hidden]d-|| import_file
file                 ||-[hidden]d-|| directory
directory            ||-[hidden]d-|| source
image_file           ||-[hidden]l-|| backup
backup               ||-[hidden]l-|| hardware
@enduml
