@startuml
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
title Refactored ERD
skinparam linetype ortho
scale 0.75

entity file_system_object {
* **id** : int <<generated>>
==
* type : char(4)
* name : varchar(200)
  parent : int **FK**
}

entity file {
   * **id** : int **FK** **PK**
   ==
   classification_id : int **FK**
   size : int
   date : datetime
   * removed : bit(1)
   md5 : varchar(32)
   flags : varchar(5)
   ==
   type = FILE
}

entity image_file {
   * **id** : int **FK** **PK**
   ==
   ==
   type = IMGE
}

entity video_file {
   * **id** : int **FK** **PK**
   ==
   ==
   type = VIDO
}

entity directory {
  * **id** : int **FK** **PK**
  ==
  * removed : bit(1)
  ==
  type = DIRY
}

entity source {
  * **id** : int **FK** **PK**
  ==
  * location : int **FK**
  status : varchar(15)
  filter : varchar(60)
  source_type : varchar(3)
  ==
  type = SRCE
}


entity import_source {
  * **id** : int **FK** **PK**
  ==
  destination : int **FK**
  ==
  type = IMPS
}

entity classification {
  * **id** : int <<generated>> **PK**
  ==
  * order int
  regex : varchar(50)
  icon : varchar(60)
  * action : varchar(20)
  * useMD5 : bit(1)
  type : varchar(30)
  is_image : bit(1)
  is_video : bit(1)
}

entity backup {
  * **id** : char(4) **PK**
  ==
  * type : varchar(50)
  * directory : varchar(300)
  * artifact : varchar(100)
  * backup_name : varchar(35)
  * filename : varchar(100)
  * time : int
}

entity hardware {
  * **macAddress** : char(17) **PK**
  ==
  * reservedIP : char(1)
  IP : varchar(15)
  * name : varchar(200)
}

entity location {
  * **id** : int **PK**
  ==
  * name : varchar(100)
  * size : varchar(10)
  check_duplicates : bit(1)
}

entity ignore_file {
  * **id** : int **FK** **PK**
  ==
  ==
  type = IGNO
}

entity import_file {
  * **id** : int **FK** **PK**
  ==
  * status : varchar(20)
  ==
  type = IMPO
}

entity synchronize {
 * **id** : int **PK**
 ==
 * source : int **FK**
 * destination : int **FK**
}

entity action_confirm {
   * **id** : int <<generated>> **PK**
   ==
   * action : varchar(20)
   * confirmed : bit(1)
   parameter_required : bit(1)
   parameter : varchar(50)
   file_id : int **FK**
   flags : varchar(10)
}

file_system_object |o--|| file_system_object : fk_fso_parent
file |o--|| file_system_object : fk_fso_file
directory |o--|| file_system_object : fk_fso_directory
source |o--|| file_system_object : fk_fso_source
image_file |o--|| file : fk_file_image
video_file |o--|| file : fk_file_video
ignore_file |o--|| file : fk_file_ignore
import_file |o--|| file : fk_file_import
import_source ||--o| source : fk_source_import
file }|--|| classification : fk_classification_file
source }|--|| location : fk_location_source
synchronize }|--|| source : fk_source_sync_src
synchronize }|--|| source : fk_source_sync_dst
action_confirm }o--|| file : fk_action_file
@enduml
